package Model;


import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

@Table("jokes")
public class Joke {
    @Id
    private Long id; // This can be auto-generated by the database
    private String setup; // Represents the joke setup
    private String punchline; // Represents the punchline

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSetup() {
        return setup;
    }

    public void setSetup(String setup) {
        this.setup = setup;
    }

    public String getPunchline() {
        return punchline;
    }

    public void setPunchline(String punchline) {
        this.punchline = punchline;
    }

	public Joke(Long id, String setup, String punchline) {
		super();
		this.id = id;
		this.setup = setup;
		this.punchline = punchline;
	}

	public Joke() {
		super();
	}
	
    
}

